<a href="https://colab.research.google.com/github/Amonmocho/Amonmocho/blob/main/GL_Algorithms_Practice_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear Regression ML Algorithm

-We are trying to train our model to be able to predict the price of houses.How can our model accuerately predict the price of houses?

In [ ]:
   import numpy as np
   import pandas as pd
import sklearn

In [ ]:
df = pd.read_csv("Boston.csv")
df

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [ ]:
import pandas as pd

df = pd.read_csv('Boston.csv')  # Use the uploaded file name
print(df.head())

   Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0           1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1
1           2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2
2           3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2
3           4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3
4           5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3

   tax  ptratio   black  lstat  medv
0  296     15.3  396.90   4.98  24.0
1  242     17.8  396.90   9.14  21.6
2  242     17.8  392.83   4.03  34.7
3  222     18.7  394.63   2.94  33.4
4  222     18.7  396.90   5.33  36.2

In [ ]:
bos1.isna().sum()

CRIM         0
ZN         507
INDUS      507
CHAS       507
NOX        507
RM         507
AGE        507
DIS        507
RAD        507
TAX        507
PTRATIO    507
B          507
LSTAT      507
MEDV       507
dtype: int64

In [ ]:
import pandas as pd

df = pd.read_csv('Boston.csv')  # Use the uploaded file name
print(df.head())

   Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0           1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1
1           2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2
2           3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2
3           4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3
4           5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3

   tax  ptratio   black  lstat  medv
0  296     15.3  396.90   4.98  24.0
1  242     17.8  396.90   9.14  21.6
2  242     17.8  392.83   4.03  34.7
3  222     18.7  394.63   2.94  33.4
4  222     18.7  396.90   5.33  36.2

In [ ]:
column_names = data.columns.tolist()  # This converts the Index object to a list
print(column_names)

NameError: name 'data' is not defined

Splitting model data with 70% for training

In [ ]:
 from sklearn.model_selection import train_test_split
 import numpy as np
 x=np.array(bos1.iloc[:,0:13])
 Y=np.array(bos1['MEDV'])
 #testing data size is of 30% of entire data
 x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.3, random_state =5)

Using Linear Regression Model

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
#load our first model
lr = LinearRegression()
#train the modelon training data
lr.fit(x_train,y_train)
#predict the testing data so that we can later evaluate the model
pred_lr = lr.predict(x_test)

Model Evaluation

In [ ]:
#error for linear
use_lr= sklearn.metrics.mean_squared_error(y_test, pred_lr,squared+False)
print("error for Linear Regression = {}".format(use_lr))

Naive Bayes Algorithm
-based on Bayes theorem
Supervised learning algorithm
Based on conditional probability

In [ ]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_metrix

In [ ]:
from google.colab import files

# Upload a file
uploaded = files.upload()

# List the uploaded files
for filename in uploaded.keys():
    print(f"Uploaded file: {filename}")

Saving ds_salaries.csv to ds_salaries.csv
Uploaded file: ds_salaries.csv

In [ ]:
import pandas as pd

# Replace 'your_file.csv' with your actual filename
df = pd.read_csv('ds_salaries.csv')
print(df.head())

   work_year experience_level employment_type                 job_title  \
0       2023               SE              FT  Principal Data Scientist
1       2023               MI              CT               ML Engineer
2       2023               MI              CT               ML Engineer
3       2023               SE              FT            Data Scientist
4       2023               SE              FT            Data Scientist

   salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0   80000             EUR          85847                 ES           100
1   30000             USD          30000                 US           100
2   25500             USD          25500                 US           100
3  175000             USD         175000                 CA           100
4  120000             USD         120000                 CA           100

  company_location company_size
0               ES            L
1               US            S
2               US            S
3               CA            M
4               CA            M

Importing training and testing dataset

In [ ]:
salary_train = pd.csv("ds_salaries.csv_Train.csv")
salary_test = pd.read_csv("ds_salaries.csv_Test.csv")
string_columns=[]
salary_trian.head()

In [ ]:
df = pd.read_csv("ds_salaries.csv")
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M
...,...,...,...,...,...,...,...,...,...,...,...
3750,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
3751,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
3752,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
3753,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
3754,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

In [ ]:
column_names = data.columns.tolist()  # This converts the Index object to a list
print(column_names)

NameError: name 'data' is not defined

In [ ]:
# Assuming 'df' contains your DataFrame, as it's used in previous cells:
column_names = df.columns.tolist()  # Replace 'data' with 'df'
print(column_names)

['work_year', 'experience_level', 'employment_type', 'job_title', 'salary', 'salary_currency', 'salary_in_usd', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']

In [ ]:
from google.colab import files
uploaded = files.upload()
import io
salary_train = pd.read_csv(io.BytesIO(uploaded['ds_salaries.csv_Train.csv']))
salary_test = pd.read_csv(io.BytesIO(uploaded['ds_salaries.csv_Test.csv']))
string_columns=['work_year', 'experience_level', 'employment_type', 'job_title', 'salary', 'salary_currency', 'salary_in_usd', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']
salary_train.head()

   Using Label Encorder-Categorical to numerical

In [ ]:
 from sklearn import preprocessing
 number = preprocessing.LabelEncoder()
 for i in string_columns:
   salary_train[i] = number.fit_transform(salary_train[i])
 salary_test[i] = number.fit_transform(salary_test[i])

NameError: name 'string_columns' is not defined

Assign the encoded variables for training and testing

In [ ]:
colnames =salary_train.columns
len(colnames[0:13])
trainX = salary_train[colnames[0:13]]
trainY = salary_train[colnames[13]]
testX = salary_test[colnames[0:13]]
testY = salary_test[colnames[13]]

NameError: name 'salary_train' is not defined

Gaussian Nave Bayes classifier for model fitting

In [ ]:
sgnb = GaussianNB ()

Predictions for test data

In [ ]:
spred_gnb = sgnb.fit(trainX,trainY).predict(testX)

Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix
cm_gnb = confusion_matrix(testY,spred_gnb)
print(cm_gnb)
print ("Accuracy" ,(10759+1209)/(10759+601+2491+1209))

NameError: name 'testY' is not defined

#KNN Algorithm

Importing the data into a pandas DataFrame

In [ ]:
import numpy as np
import pandas as pd
import sklearn
column_names = ['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'black', 'lstat', 'medv']
df = pd.read_csv("Boston.csv" , delimiter=r"\s+", names=column_names)
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,",crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"1,0.00632,18,2.31,0,0.538,6.575,65.2,4.09,1,29...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"2,0.02731,0,7.07,0,0.469,6.421,78.9,4.9671,2,2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"3,0.02729,0,7.07,0,0.469,7.185,61.1,4.9671,2,2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"4,0.03237,0,2.18,0,0.458,6.998,45.8,6.0622,3,2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.isna().sum()

crim         0
zn         507
indus      507
chas       507
nox        507
rm         507
age        507
dis        507
rad        507
tax        507
ptratio    507
black      507
lstat      507
medv       507
dtype: int64

In [ ]:
# Assuming 'df' contains your DataFrame, as it's used in previous cells:
column_names = df.columns.tolist()  # Replace 'data' with 'df'
print(column_names)

['Unnamed: 0', 'crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'black', 'lstat', 'medv']

In [ ]:
df = pd.read_csv("Boston.csv")
df

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

Splitting model data with 70% for training

In [ ]:
from sklearn.model_selection import train_test_split
x.np.array(df.iloc[:,0:13])
Y=np.array(df['MEDV'])
#testing data size is of 30% of entire data
x_train,x_test,y_train,y_test=train_test_split(X,Y test_size = 0.30, random_state=5)

Using KNN Algorithm

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
#train the model on training data
lr.fit(x_train,y_train)
#load the KNN Model
Nn=KNeighborsRegressor(3)
Nn.fit(X_train,y_train)

pred_Nn = Nn.predict(x_test)

NameError: name 'lr' is not defined

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
# Initialize the LinearRegression model
lr = LinearRegression()  # This line was added
#train the model on training data
lr.fit(x_train,y_train)
#load the KNN Model
Nn=KNeighborsRegressor(3)
Nn.fit(x_train,y_train)

pred_Nn = Nn.predict(x_test)

Hyperparameter Tuning

In [ ]:
  import sklearn
  for i in range(1,50)
  model=KNeighborsRegressor(i)
  model.fit(x_train,y_train)
  pred_y = model.predict(x_test)
  mse = sklearn.metrics.mean_squared_error(y_test, pred_Y,squared+False)
  print("{} error for k = {}",format(mse,i))

SyntaxError: expected ':' (<ipython-input-31-0a45cb99e00e>, line 2)

Model Evaluation

In [ ]:
#Error for KNN Algorithm
mse_Nn = sklearn.metrics.mean_squared_error(y_test, pred_Nn,squared+False)
print("error for KNN = {}".format(mse_Nn))

NameError: name 'y_test' is not defined

#Support Vector Machines(SVM)

-Considered as a black box technique due to presence of unkwown parameters.
-Data separation for non-linear classes are one using Kernel tricks
-Parameters are turned using Kernel functions

Popular in Banking and Health Care industry

Importing all Libraries

In [ ]:
  import numpy as np
  import matplotlib.pyplot as plt
  import pandas as pd

Importing the dataset

In [ ]:
dataset = pd.read_csv('')
dataset.head()

Filtering out columns to retain age and salary columns

In [ ]:
X = dataset.iloc[:,[2,3]].values
y = dataset.iloc[:,4].values

Scaling using Standard Scaler for Normal Distribution

In [ ]:
from sklearn.preprocessing import standardscaler
sc  = Standardscaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Building the model Using RBF Kernel

In [ ]:
from sklearn.svm import SVC
classifier_rdf= SVC(kernel = 'rbf', random_state = 0)
classifier_rdf.fit(X_train,y_train)
y_pred = classifier_rdf.predict(X_test)

Printing the conclusion Metrix

In [ ]:
from sklearn.metrics import confusion_matrix
cm_rbf = confusion_matrix(y_test,y_pred_rbf)
print(cm_rbf)

Classification Report

In [ ]:
from sklearn.metrics import classification_report
class_report_rbf=classification_report(y_test,y_pred_rbf))
print(class_report_rbf)

#Random Forest Algorithm

Works oth for classification and regression Problems
.Automation of missing values is possible
Required computation power for complex trees.

In [ ]:
import numpy as np
import matplotli.pylot as plt
import pandas as pd
df = pd.read_csv("Boston.csv")
df.head()

In [ ]:
 X = df.iloc[:, 1:2].values
 Y = df.iloc[:, 2].values

Model fittting with 10 trees

In [ ]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators = 10, random_state = 0)
model.fit(X, Y)

Prediction of salary with level>6.5

In [ ]:
y_pred = model.predict(np.array([[6.5]]))

Visualisation of the result

In [ ]:
x_grid = np.arange(min(X), max(X), 0.01)
x_grid = x_grid.reshape((len(x_grid_data), 1))
plt.scatter(X, Y, color = 'red')
plt.plot(x_grid, model.predict(x_grid), color = 'blue')
plt.title(Random Forest Regression)')
plt.xlabel('Position')
plt.ylabel('Salary')
plt.show()